name: Build and Release

on:
  push:
    branches: [ main, beta, 2.x ]
  pull_request:
    branches: [ main, beta, 2.x ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - uses: actions/upload-artifact@v6
        with:
          name: eliminami-artifacts
          path: dist

  release:
    permissions:
      id-token: write  # Required for OIDC
      contents: write
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - uses: actions/download-artifact@v7
        with:
          name: eliminami-artifacts
          path: dist

      - uses: cycjimmy/semantic-release-action@v6
        with:
          semantic_version: 25.0.1
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
